spring.application.name=chatbot
#spring.datasource.url=jdbc:postgresql://132.248.32.197:5433/chatbot
spring.datasource.url=jdbc:postgresql://132.248.32.197:5433/chatbot
spring.datasource.username=agent_ia
spring.datasource.password=uusmb_ia2025
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Ver querys
spring.jpa.show-sql=true

# Loggers
logging.level.root=info
logging.file.name=servicio_test.log
logging.level.com.example.conexionbd=info

# Security
jwt.secret=Y2hhbkdsamFoNkFwNGpxdnillrcEVrcG5LMzNiZGpLNGNPaXFvaGVwZzFkZw==
jwt.expiration=864000000
