spring.application.name=chatbot
spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Ver querys
spring.jpa.show-sql=true

# Loggers
logging.level.root=info
logging.file.name=servicio_test.log
logging.level.com.example.conexionbd=info

# Security
jwt.secret=Y2hhbkdsamFoNkFwNGpxdnillrcEVrcG5LMzNiZGpLNGNPaXFvaGVwZzFkZw==
jwt.expiration=864000000
